### ISSUE TITLE
"dropped a sig due to decompilation failure."

### ISSUE THREAD

**Issue by JillCrungus** [ajkhoury/SigMaker-x64#20]
Hi. I've not really worked with this kind of thing before and I'm having an issue where I can't seem to generate any signatures at all. It was just giving me a fail message but upon turning up the logger level I found that every attempt failed with the message:
"dropped a sig due to decompilation failure."

I'm not sure if this is normal, if I'm doing something wrong or if something is actually broken with the plugin. It'd be great to get some help. This seems to happen with any and every function I try to generate a sig for which is what makes me think this isn't normal.

**Comment by gir489** [comment]
I believe this is an issue of PEBKAC. SigMaker only works with x86 binaries. Looking at the error from the source code, it’s thrown from a failure scenario for an IDA function.

**Comment by JillCrungus** [comment]
> I believe this is an issue of PEBKAC. SigMaker only works with x86 binaries. Looking at the error from the source code, it’s thrown from a failure scenario for an IDA function.

The binary is x86, seems like it is a problem with this specific binary though because I quickly tested it on something else and it worked fine. I don't know what the problem would be though.

**Comment by ajkhoury** [comment]
Can you please provide the region of bytes you are trying to generate a signature for? This error will occur if you try to automatically generate a signature on any bytes that are not encoded as x86 instructions. E.g. if the region of code has been virtualized, or if you try to generate a signature on the data segment of an executable.

**Comment by ajkhoury** [comment]
> > Can you please provide the region of bytes you are trying to generate a signature for? This error will occur if you try to automatically generate a signature on any bytes that are not encoded as x86 instructions. E.g. if the region of code has been virtualized, or if you try to generate a signature on the data segment of an executable.
> 
> What's the best way for me to provide it?

Go to Options > General and then set the "Number of opcode bytes (non-graph)" to something like 10.

![](https://i.imgur.com/16bOQRq.jpg)

Then you'll see the disassembly output look like this:

![](https://i.imgur.com/OVpCxU0.png)

Just take a picture of the region you're trying to auto generate a signature for, or just paste the bytes in your reply.

**Comment by JillCrungus** [comment]
> Just take a picture of the region you're trying to auto generate a signature for, or just paste the bytes in your reply.

Here's a picture of one of the smaller functions.
![image](https://user-images.githubusercontent.com/32760843/48849569-8a8e5700-ed9e-11e8-99db-1fc4fc802051.png)

I can't tell myself if there's anything really wrong with it, just looks like any other disassembly to me. Maybe there is something wrong with it like you said. I seem to get the error no matter where I try to generate a signature for in this executable.

**Comment by ajkhoury** [comment]
Could you upload the executable? I'd like to check it myself and see if I can reproduce. I don't see a reason why this should be throwing this error.

**Comment by JillCrungus** [comment]
> Could you upload the executable? I'd like to check it myself and see if I can reproduce. I don't see a reason why this should be throwing this error.

Sure thing. Damn sure this thing is cursed.

[dr1_us.zip](https://github.com/ajkhoury/SigMaker-x64/files/2604712/dr1_us.zip)

**Comment by ajkhoury** [comment]
At the same function in your screenshot I can generate a signature without problems 🤔 

```
added a total of 83 references.
direct reference: [actual address in first opcode] E8 ? ? ? ? 8B 43 48
```

**Comment by JillCrungus** [comment]
> At the same function in your screenshot I can generate a signature without problems 
> 
> ```
> added a total of 83 references.
> direct reference: [actual address in first opcode] E8 ? ? ? ? 8B 43 48
> ```

Huh, that means it's something on my end then. Strange because I can generate signatures for other binaries with no problems, only this one is giving me trouble.

**Comment by ajkhoury** [comment]
> > At the same function in your screenshot I can generate a signature without problems
> > ```
> > added a total of 83 references.
> > direct reference: [actual address in first opcode] E8 ? ? ? ? 8B 43 48
> > ```
> 
> Huh, that means it's something on my end then. Strange because I can generate signatures for other binaries with no problems, only this one is giving me trouble.

One thing I noticed in your screenshot is that your binary is loaded at address 00C20000, which is not a standard image base for a win32 executable to be loaded at. What options did you choose when first disassembling the file?

**Comment by gir489** [comment]
Confirmed for PEBCAK as I previously predicted. Closing.
