### ISSUE TITLE
IDA 7.2 - "Test code pattern" dialog doesn't pop up

### ISSUE THREAD

**Issue by papstuc** [ajkhoury/SigMaker-x64#28]
When I'm pressing "Test code pattern" in the main form nothing happens. "Test ida pattern" works completely fine and gives me a pop up where I have the insert the pattern. 

I'm pretty sure I'm missing something.

Kind regards

**Comment by gir489** [comment]
I was able to reproduce this issue, but I don't have the IDASDK anymore to fix it. Someone else will have to take it. Thanks for the report.

**Comment by papstuc** [comment]
> I was able to reproduce this issue, but I don't have the IDASDK anymore to fix it. Someone else will have to take it. Thanks for the report.

I tried selecting a big chunk of code and then the window was popping up.
I will make a pull request for this tomorrow

**Comment by gir489** [comment]
> I tried selecting a big chunk of code and then the window was popping up. I will make a pull request for this tomorrow
Oh right I forgot that. That's expected behaviour, it needs to have some bytecode to generate a code signature for. @ajkhoury should this be changed? I feel like this is more of a design issue.

**Comment by papstuc** [comment]
> > I tried selecting a big chunk of code and then the window was popping up. I will make a pull request for this tomorrow
> 
> Oh right I forgot that. That's expected behaviour, it needs to have some bytecode to generate a code signature for. @ajkhoury should this be changed? I feel like this is more of a design issue.

I recently moved from IDA 6.8 to 7.
The old sigmaker plug-in from unknowncheats doesn't require this.
Probably selects some code in the background tho.

**Comment by papstuc** [comment]
I have now updated and tested it for a while and it works like a charm without selecting any code
