### ISSUE TITLE
The plugin does not work after using the "Rebase program".

### ISSUE THREAD

**Issue by Tim4ukys** [ajkhoury/SigMaker-x64#31]
After I change the base address, "SigMarker" stops working (search for patterns and automatically generate them).
![image](https://user-images.githubusercontent.com/73384372/179269289-c7b584fc-49e8-4a78-bb20-ec6551c1832e.png)

**Comment by Tim4ukys** [comment]
Found the cause of the problem. This is due to the fact that the data "omin_ea" and "omax_ea" are not updated in the "idainfo" structure.
![image](https://user-images.githubusercontent.com/73384372/179354289-33af04df-7e6b-4935-a2ee-e70c1998f5db.png)
![image](https://user-images.githubusercontent.com/73384372/179354268-0c3cc864-db70-42cd-9504-c506d72043df.png)

**Comment by Tim4ukys** [comment]
I found a solution. It is necessary to use not "omin_ea" and "omax_ea", but "min_ea" and "max_ea". This is due to the fact that after changing the position of the segments, you need to use not the original (old) one, but the one that is now.

---
Output window:
![Output window](https://user-images.githubusercontent.com/73384372/179354512-953d91f0-2a41-479f-88c6-0d721b88ed43.png)

Code: 
![image](https://user-images.githubusercontent.com/73384372/179354549-cc188b97-a42b-4676-a64e-389c938fffa2.png)

**Comment by ajkhoury** [comment]
Nice, thanks for this. You can cut a PR if you'd like.

**Comment by tunip3** [comment]
would it be possible to update the release to add the fixed version?

**Comment by fred0r** [comment]
> would it be possible to update the release to add the fixed version?

yes
