### ISSUE TITLE
How to build plugins for Win32 platform?

### ISSUE THREAD

**Issue by RyderFL** [ajkhoury/SigMaker-x64#34]
First of all, i am very sorry. it's actually not an issus about this plugin.

I am using this [ida sdk](https://github.com/helloobaby/idasdk76) on Windows with VS2019. And writed a simple plugin. I can build for x64 platform. and it works.

But for x86 platform, the compiler tells "error LNK2001: unresolved external symbol \_qgetenv@8". The compiler added a "\_" and "@8" to the function qgetenv. I checked that there is an export "qgetenv" in <IDASDK>\x64_win_vc_32\ida.lib. 

the declare of function in idasdk is:
extern "C" bool __stdcall qgetenv(const char *varname, DEFARG(qstring *buf,NULL));

i googled, it means "\_" and "@" is added by __stdcall. I tried __cdecl, but the external symbol changed to "\_qgetenv". 

Could you help me about this ? Thanks a lot

**Comment by ajkhoury** [comment]
x86 plugins are not supported by IDA Pro since version 7.0. You're trying to link an 64-bit library in an 32-bit binary, which symbol mangling is different between the two target architectures, that's why you're getting that error.

**Comment by RyderFL** [comment]
Thanks. 
It's means x64_win_vc_32 is also for x64 platform but 32bit visual studio. That right?
If so, how to support ida.exe(not ida64.exe)? I found many plugins for ida.exe under plugins folder.

**Comment by RyderFL** [comment]
Thanks again.
I found the answer. Just build a x64 plugin link with x64_win_vc_32\ida.lib.
